apiVersion: apps/v1
kind: Deployment
metadata:
  name: aliyunpan-sign
  namespace: app
spec:
  selector:
    matchLabels:
      app: aliyunpan-sign
  template:
    metadata:
      labels:
        app: aliyunpan-sign
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: aliyunpan-sign
        image: replace
        env:
        - name: DING_SECRET
          value: ""
        - name: DINGDING_BASE_URL
          value: ""
        - name: TIME
          value: ""
        - name: REFRESH_TOKEN_LIST
          value: ""
        - name: TZ
          value: Asia/Shanghai
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

